# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sql:
    container_name: "tecjobsdb"
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=#yma2578k
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  tecjobsapi:
    container_name: "tecjobsapi"
    image: tecjobsapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    networks:
      - techjobs-network

networks:
  techjobs-network:
    driver: bridge
